name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: sbt GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
        run: |
          echo "Run] sbt GitHub release"
          echo "mkdir -p dotty-docs"
          mkdir -p dotty-docs
          export SOURCE_DATE_EPOCH=$(date +%s)
          echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH"
          echo 'sbt -J-Xmx2048m clean +test +packagedArtifacts gitHubRelease'
          sbt -J-Xmx2048m \
            clean \
            +test \
            +packagedArtifacts \
            gitHubRelease


  publish:
    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { name: "Scala 2", version: "2.10.7",    binary-version: "2.10",      java-version: "adopt@1.8" }
          - { name: "Scala 2", version: "2.11.12",   binary-version: "2.11",      java-version: "adopt@1.8" }
          - { name: "Scala 2", version: "2.12.13",   binary-version: "2.12",      java-version: "adopt@1.11" }
          - { name: "Scala 2", version: "2.13.5",    binary-version: "2.13",      java-version: "adopt@1.11" }
          - { name: "Scala 3", version: "3.0.0-M1",  binary-version: "3.0.0-M1",  java-version: "adopt@1.11" }
          - { name: "Scala 3", version: "3.0.0-M2",  binary-version: "3.0.0-M2",  java-version: "adopt@1.11" }
          - { name: "Scala 3", version: "3.0.0-M3",  binary-version: "3.0.0-M3",  java-version: "adopt@1.11" }
          - { name: "Scala 3", version: "3.0.0-RC1", binary-version: "3.0.0-RC1", java-version: "adopt@1.11" }
          - { name: "Scala 3", version: "3.0.0-RC2", binary-version: "3.0.0-RC2", java-version: "adopt@1.11" }

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.scala.java-version }}

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}

      - name: "sbt publish for ${{ matrix.scala.name }} ${{ matrix.scala.version }} - ${{ github.run_number }}"
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: |
          echo "Run] sbt publish for Scala ${{ matrix.scala.version }}"
          echo "mkdir -p dotty-docs"
          mkdir -p dotty-docs
          export SOURCE_DATE_EPOCH=$(date +%s)
          echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH"
          echo 'sbt -J-Xmx2048m ++${{ matrix.scala.version }}! -v clean publish'
          sbt \
            -J-Xmx2048m \
            ++${{ matrix.scala.version }}! \
            -v \
            clean \
            publish

  publish_maven:
    needs: publish
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync to Maven Central
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: |
          export GITHUB_TAG=${GITHUB_REF#refs/tags/}
          .github/workflows/maven_central_sync.sh
